<?php
namespace MathCourse;
defined('ABSPATH') || exit;
class Plugin {
 public function run(){$this->load_modules();$this->load_assets();$this->load_admin_assets();}
 private function load_modules(){
  if(class_exists('MathCourse\\Access\\Access_Service'))new Access\Access_Service();if(class_exists('MathCourse\\Access\\Activation_Schema'))new Access\Activation_Schema();if(class_exists('MathCourse\\Access\\Activation_Service'))new Access\Activation_Service();if(class_exists('MathCourse\\Tutor\\Adapter'))new Tutor\Adapter();if(class_exists('MathCourse\\Progress\\Progress_Service'))new Progress\Progress_Service();if(class_exists('MathCourse\\Admin\\Menu'))new Admin\Menu();if(class_exists('MathCourse\\Admin\\Frontend_Settings'))new Admin\Frontend_Settings();if(class_exists('MathCourse\\Admin\\Lesson_Topic'))new Admin\Lesson_Topic();if(class_exists('MathCourse\\Admin\\Activation_Page'))new Admin\Activation_Page();if(class_exists('MathCourse\\Admin\\Course_Actions'))new Admin\Course_Actions();if(class_exists('MathCourse\\Admin\\Course_Sort'))new Admin\Course_Sort();if(class_exists('MathCourse\\Admin\\Batch_Manager_V2'))new Admin\Batch_Manager_V2();if(class_exists('MathCourse\\Admin\\Course_Trash_Page'))new Admin\Course_Trash_Page();if(class_exists('MathCourse\\Admin\\Student_Page'))new Admin\Student_Page();if(class_exists('MathCourse\\Course\\Meta'))new Course\Meta();if(class_exists('MathCourse\\Course\\Lesson_Meta'))new Course\Lesson_Meta();if(class_exists('MathCourse\\Course\\Course_Service'))new Course\Course_Service();if(class_exists('MathCourse\\Progress\\Progress_Ajax'))new Progress\Progress_Ajax();if(class_exists('MathCourse\\Tutor\\Hooks'))new Tutor\Hooks();if(class_exists('MathCourse\\Learning\\Lesson_Status'))new Learning\Lesson_Status();if(class_exists('MathCourse\\Learning\\Course_Learning'))new Learning\Course_Learning();if(class_exists('MathCourse\\Video\\Player'))new Video\Player();if(class_exists('MathCourse\\Video\\Video_Router'))new Video\Video_Router();if(class_exists('MathCourse\\Video\\Hls_Accelerator'))new Video\Hls_Accelerator();if(class_exists('MathCourse\\Video\\Local_Hls_Source'))new Video\Local_Hls_Source();if(class_exists('MathCourse\\Video\\Hls_Converter'))new Video\Hls_Converter();if(class_exists('MathCourse\\Frontend\\Activation'))new Frontend\Activation();if(class_exists('MathCourse\\Frontend\\Student_Auth'))new Frontend\Student_Auth();if(class_exists('MathCourse\\Frontend\\Course_Directory'))new Frontend\Course_Directory();if(class_exists('MathCourse\\Frontend\\Course_Player'))new Frontend\Course_Player();if(class_exists('MathCourse\\Frontend\\Course_Directory_Assets'))new Frontend\Course_Directory_Assets();
 }
 private function load_assets(){add_action('wp_enqueue_scripts',function(){wp_enqueue_style('mathcourse',MATHCOURSE_URL.'assets/css/mathcourse.css',array(),MATHCOURSE_VERSION);if(is_singular()){global $post;if($post&&has_shortcode($post->post_content,'math_student_register'))wp_enqueue_style('mathcourse-activation',MATHCOURSE_URL.'assets/css/activation.css',array('mathcourse'),MATHCOURSE_VERSION);}});}
 private function load_admin_assets(){add_action('admin_enqueue_scripts',function(){wp_enqueue_style('mathcourse-admin',MATHCOURSE_URL.'assets/css/admin.css',array(),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-redesign',MATHCOURSE_URL.'assets/css/admin-redesign.css',array('mathcourse-admin'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-ui',MATHCOURSE_URL.'assets/admin-ui.css',array('mathcourse-admin-redesign'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-access',MATHCOURSE_URL.'assets/admin-access.css',array('mathcourse-admin-ui'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-progress',MATHCOURSE_URL.'assets/admin-progress.css',array('mathcourse-admin-access'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-settings',MATHCOURSE_URL.'assets/admin-settings.css',array('mathcourse-admin-progress'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-activation',MATHCOURSE_URL.'assets/admin-activation.css',array('mathcourse-admin-settings'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-activation-admin',MATHCOURSE_URL.'assets/css/activation.css',array('mathcourse-admin-activation'),MATHCOURSE_VERSION);wp_enqueue_style('mathcourse-admin-course-list-compact',MATHCOURSE_URL.'assets/admin-course-list-compact.css',array('mathcourse-admin-ui'),MATHCOURSE_VERSION);wp_enqueue_script('mathcourse-admin-course-editor',MATHCOURSE_URL.'assets/js/admin-course-editor.js',array(),MATHCOURSE_VERSION,true);wp_enqueue_script('mathcourse-admin-video-upload',MATHCOURSE_URL.'assets/js/admin-video-upload.js',array('mathcourse-admin-course-editor'),MATHCOURSE_VERSION,true);wp_enqueue_script('mathcourse-admin-video-upload-fix',MATHCOURSE_URL.'assets/js/admin-video-upload-fix.js',array('mathcourse-admin-video-upload'),MATHCOURSE_VERSION,true);wp_enqueue_script('mathcourse-admin-lesson-topic',MATHCOURSE_URL.'assets/js/admin-lesson-topic.js',array('mathcourse-admin-video-upload-fix'),MATHCOURSE_VERSION,true);wp_localize_script('mathcourse-admin-video-upload','mathcourseVideoAdmin',array('ajax_url'=>admin_url('admin-ajax.php'),'nonce'=>wp_create_nonce('mathcourse_video_upload')));wp_enqueue_style('mathcourse-admin-video-upload',MATHCOURSE_URL.'assets/admin-video-upload.css',array('mathcourse-admin-ui'),MATHCOURSE_VERSION);});}
}
