import Foundation
import Metal
import MetalKit
import simd

final class InkRenderer: NSObject, MTKViewDelegate {
    enum SelectionHandle { case topLeft, topRight, bottomLeft, bottomRight }
    private struct Uniforms { var viewportSize: SIMD2<Float> }
    private struct StoredStroke: Equatable { var id: UUID; var points: [InkPoint]; var style: PenStyle; var rotation: Float = 0 }
    private struct HistoryState { var strokes: [StoredStroke]; var objects: [GraphicObject]; var selection: [Int]; var objectSelection: [UUID] }
    private let device: any MTLDevice
    private let commandQueue: any MTLCommandQueue
    private let pipelineState: any MTLRenderPipelineState
    private var committedStrokes: [StoredStroke] = []
    private var objectStore = GraphicObjectStore()
    private var activeStroke: [InkPoint] = []
    private var vertices: [InkVertex] = []
    private var vertexBuffer: (any MTLBuffer)?
    private var uniformBuffer: (any MTLBuffer)?
    private var penStyle = PenStyle()
    private(set) var selectedStrokeIndices: [Int] = []
    private(set) var selectedObjectIDs: [UUID] = []
    private var customRotationCenter: SIMD2<Float>?
    private var backgroundColor = SIMD4<Float>(1, 1, 1, 1)
    private var displayInverted = false
    private var backgroundPattern = 0
    private var panOffset = SIMD2<Float>(0, 0)
    private var zoomScale: Float = 1
    private var undoStack: [HistoryState] = []
    private var redoStack: [HistoryState] = []
    private var transactionStart: HistoryState?
    private var pasteCascadeIndex = 0
    private var lastClipboardPayloadData: Data?

    init?(device: any MTLDevice) {
        guard let queue = device.makeCommandQueue(), let library = try? device.makeDefaultLibrary(bundle: Bundle.module), let vf = library.makeFunction(name: "inkVertex"), let ff = library.makeFunction(name: "inkFragment") else { return nil }
        let descriptor = MTLRenderPipelineDescriptor(); descriptor.vertexFunction = vf; descriptor.fragmentFunction = ff; descriptor.colorAttachments[0].pixelFormat = .bgra8Unorm; descriptor.colorAttachments[0].isBlendingEnabled = true; descriptor.colorAttachments[0].sourceRGBBlendFactor = .sourceAlpha; descriptor.colorAttachments[0].destinationRGBBlendFactor = .oneMinusSourceAlpha; descriptor.colorAttachments[0].sourceAlphaBlendFactor = .sourceAlpha; descriptor.colorAttachments[0].destinationAlphaBlendFactor = .oneMinusSourceAlpha
        guard let pipeline = try? device.makeRenderPipelineState(descriptor: descriptor) else { return nil }; self.device=device; self.commandQueue=queue; self.pipelineState=pipeline; super.init()
    }
    var canUndo: Bool { !undoStack.isEmpty }
    var canRedo: Bool { !redoStack.isEmpty }
    var hasSelection: Bool { !selectedStrokeIndices.isEmpty || !selectedObjectIDs.isEmpty }
    var selectionCount: Int { selectedStrokeIndices.count + selectedObjectIDs.count }
    var selectedStrokeIndex: Int? { selectedObjectIDs.isEmpty && selectedStrokeIndices.count == 1 ? selectedStrokeIndices[0] : nil }
    var zoomPercent: Int { Int((zoomScale * 100).rounded()) }
    var selectedRotationDegrees: Double { if selectedObjectIDs.count == 1, let id=selectedObjectIDs.first, let object=objectStore.object(with:id) { return Double(object.transform.rotation)*180/Double.pi }; guard let index=selectedStrokeIndex, committedStrokes.indices.contains(index) else { return 0 }; return Double(committedStrokes[index].rotation)*180/Double.pi }
    func setPenStyle(_ style: PenStyle) { penStyle=style; rebuildGeometry() }
    func setBackgroundColor(_ color: SIMD4<Float>) { backgroundColor=color; rebuildGeometry() }
    func setDisplayInverted(_ value: Bool) { displayInverted=value; rebuildGeometry() }
    func setBackgroundPattern(_ value: Int) { backgroundPattern=value; rebuildGeometry() }
    func setStroke(_ points:[InkPoint]) { activeStroke=points; rebuildGeometry() }
    func canvasPoint(from point:SIMD2<Float>)->SIMD2<Float>{(point-panOffset)/zoomScale}
    func viewPoint(from point:SIMD2<Float>)->SIMD2<Float>{point*zoomScale+panOffset}
    func pan(by delta:SIMD2<Float>){panOffset += delta; rebuildGeometry()}
    func zoom(by factor:Float, around point:SIMD2<Float>){let c=canvasPoint(from:point); zoomScale=min(max(zoomScale*factor,0.25),4); panOffset=point-c*zoomScale; rebuildGeometry()}
    func resetZoom(centeredIn size:CGSize){zoomScale=1;panOffset=SIMD2(Float(size.width/2),Float(size.height/2));rebuildGeometry()}
    func exportPageState()->CanvasPageState{CanvasPageState(strokes:committedStrokes.map{CanvasStroke(id:$0.id,points:$0.points,style:$0.style,rotation:$0.rotation)},objects:objectStore.exportObjects())}
    func importPageState(_ state:CanvasPageState){committedStrokes=state.strokes.map{StoredStroke(id:$0.id,points:$0.points,style:$0.style,rotation:$0.rotation)};objectStore.importObjects(state.objects);activeStroke=[];selectedStrokeIndices=[];selectedObjectIDs=[];customRotationCenter=nil;undoStack=[];redoStack=[];transactionStart=nil;pasteCascadeIndex=0;lastClipboardPayloadData=nil;rebuildGeometry()}
    func beginHistoryTransaction(){if transactionStart == nil{transactionStart=captureState()}}
    func endHistoryTransaction(){guard let before=transactionStart else{return};transactionStart=nil;let after=captureState();if before.strokes != after.strokes || before.objects != after.objects || before.selection != after.selection || before.objectSelection != after.objectSelection{undoStack.append(before);redoStack.removeAll()}}
    private func recordMutation(){guard transactionStart == nil else{return};undoStack.append(captureState());redoStack.removeAll()}
    private func captureState()->HistoryState{HistoryState(strokes:committedStrokes,objects:objectStore.exportObjects(),selection:selectedStrokeIndices,objectSelection:selectedObjectIDs)}
    private func restore(_ state:HistoryState){committedStrokes=state.strokes;objectStore.importObjects(state.objects);selectedStrokeIndices=state.selection.filter{committedStrokes.indices.contains($0)};selectedObjectIDs=state.objectSelection.filter{objectStore.object(with:$0) != nil};customRotationCenter=nil;rebuildGeometry()}
    func undo(){guard let state=undoStack.popLast() else{return};redoStack.append(captureState());restore(state)}
    func redo(){guard let state=redoStack.popLast() else{return};undoStack.append(captureState());restore(state)}
    func commitStroke(_ points:[InkPoint]){guard points.count>=2 else{activeStroke=[];rebuildGeometry();return};recordMutation();committedStrokes.append(StoredStroke(id:UUID(),points:points,style:penStyle));selectedStrokeIndices=[];selectedObjectIDs=[];activeStroke=[];rebuildGeometry()}
    func commitLine(from start:SIMD2<Float>,to end:SIMD2<Float>){recordMutation();let style=GraphicObject.Style(strokeColor:penStyle.color,strokeWidth:penStyle.width,opacity:penStyle.opacity,lineStyle:penStyle.lineStyle,fillEnabled:false,fillColor:.black,fillOpacity:0);_ = objectStore.addLine(from:CGPoint(x:CGFloat(start.x),y:CGFloat(start.y)),to:CGPoint(x:CGFloat(end.x),y:CGFloat(end.y)),style:style);selectedStrokeIndices=[];selectedObjectIDs=[];activeStroke=[];rebuildGeometry()}
    func commitPolygon(points:[CGPoint]){guard points.count>=3 else{return};recordMutation();let style=GraphicObject.Style(strokeColor:penStyle.color,strokeWidth:penStyle.width,opacity:penStyle.opacity,lineStyle:penStyle.lineStyle,fillEnabled:false,fillColor:.black,fillOpacity:0);_ = objectStore.addPolygon(points:points,style:style);selectedStrokeIndices=[];selectedObjectIDs=[];activeStroke=[];rebuildGeometry()}
    @discardableResult func commitDynamicAngle(at point:SIMD2<Float>,angleDegrees:CGFloat=45)->UUID{recordMutation();let style=GraphicObject.Style(strokeColor:penStyle.color,strokeWidth:penStyle.width,opacity:penStyle.opacity,lineStyle:penStyle.lineStyle,fillEnabled:false,fillColor:.black,fillOpacity:0);let id=objectStore.addDynamicAngle(vertex:CGPoint(x:CGFloat(point.x),y:CGFloat(point.y)),angleDegrees:angleDegrees,style:style);selectedStrokeIndices=[];selectedObjectIDs=[id];activeStroke=[];rebuildGeometry();return id}
    @discardableResult func setSelectedDynamicAngle(_ degrees:CGFloat)->Bool{guard selectedObjectIDs.count==1,let id=selectedObjectIDs.first else{return false};guard objectStore.setDynamicAngle(id:id,degrees:degrees) else{return false};rebuildGeometry();return true}
    func dynamicAngleValue()->CGFloat?{guard selectedObjectIDs.count==1,let id=selectedObjectIDs.first else{return nil};return objectStore.dynamicAngleParameter(id:id)?.value}
    @discardableResult func dynamicAngleEndpoint(at point:SIMD2<Float>,tolerance:Float=16)->UUID?{guard selectedObjectIDs.count==1,let id=selectedObjectIDs.first,let object=objectStore.object(with:id),object.kind == .dynamicAngle else{return nil};let p=canvasPoint(from:point);guard let dynamic=object.dynamicAngleModel,let end=dynamic.model.points.first(where:{$0.id == dynamic.endPointID}) else{return nil};let ep=object.transform.position;let tp=CGPoint(x:end.position.x+ep.x,y:end.position.y+ep.y);return hypot(tp.x-CGFloat(p.x),tp.y-CGFloat(p.y)) <= CGFloat(tolerance/zoomScale) ? id:nil}
    @discardableResult func moveDynamicAngleEndpoint(id:UUID,to point:SIMD2<Float>)->Bool{let p=canvasPoint(from:point);guard objectStore.dragDynamicAngleEndpoint(id:id,to:CGPoint(x:CGFloat(p.x),y:CGFloat(p.y))) else{return false};rebuildGeometry();return true}
    @discardableResult func selectObject(at point:SIMD2<Float>,tolerance:Float=10,operation:SelectionOperation=.replace)->Bool{let p=canvasPoint(from:point);guard let id=objectStore.hitTest(at:CGPoint(x:CGFloat(p.x),y:CGFloat(p.y)),tolerance:CGFloat(tolerance/zoomScale)) else{if operation == .replace{clearSelection()};return false};applySelection(operation,objects:[id],strokes:[]);return true}
    @discardableResult func toggleObject(at point:SIMD2<Float>,tolerance:Float=10)->Bool{let p=canvasPoint(from:point);guard let id=objectStore.hitTest(at:CGPoint(x:CGFloat(p.x),y:CGFloat(p.y)),tolerance:CGFloat(tolerance/zoomScale)) else{return false};if selectedObjectIDs.contains(id){selectedObjectIDs.removeAll{$0 == id}}else{selectedObjectIDs.append(id)};customRotationCenter=nil;rebuildGeometry();return true}
    @discardableResult func selectObjects(in viewRect:CGRect,fullyContained:Bool=false,operation:SelectionOperation=.replace)->Int{let a=canvasPoint(from:SIMD2(Float(viewRect.minX),Float(viewRect.minY)));let b=canvasPoint(from:SIMD2(Float(viewRect.maxX),Float(viewRect.maxY)));let r=CGRect(x:CGFloat(min(a.x,b.x)),y:CGFloat(min(a.y,b.y)),width:CGFloat(abs(a.x-b.x)),height:CGFloat(abs(a.y-b.y)));let ids=objectStore.objectsIntersecting(r,fullyContained:fullyContained);applySelection(operation,objects:ids,strokes:[]);return selectionCount}
    func clearSelection(){selectedStrokeIndices=[];selectedObjectIDs=[];customRotationCenter=nil;rebuildGeometry()}
    private func applySelection(_ operation:SelectionOperation,objects:[UUID],strokes:[Int]){switch operation{case .replace:selectedObjectIDs=objects;selectedStrokeIndices=strokes;case .add:for id in objects where !selectedObjectIDs.contains(id){selectedObjectIDs.append(id)};for index in strokes where !selectedStrokeIndices.contains(index){selectedStrokeIndices.append(index)};case .subtract:selectedObjectIDs.removeAll{objects.contains($0)};selectedStrokeIndices.removeAll{strokes.contains($0)}};customRotationCenter=nil;rebuildGeometry()}
    func selectionBounds()->CGRect?{var result:CGRect?;for i in selectedStrokeIndices{if committedStrokes.indices.contains(i),let b=bounds(committedStrokes[i].points){result=result?.union(b) ?? b}};for id in selectedObjectIDs{if let b=objectStore.bounds(of:id){result=result?.union(b) ?? b}};return result?.insetBy(dx:-8,dy:-8)}
    func selectionCenter()->SIMD2<Float>?{guard let r=selectionBounds() else{return nil};return SIMD2(Float(r.midX),Float(r.midY))}
    func moveSelected(by delta:SIMD2<Float>){for id in selectedObjectIDs{guard let o=objectStore.object(with:id) else{continue};let p=o.transform.position;_ = objectStore.transform(id:id,position:CGPoint(x:p.x+CGFloat(delta.x),y:p.y+CGFloat(delta.y)))};for i in selectedStrokeIndices where committedStrokes.indices.contains(i){committedStrokes[i].points=committedStrokes[i].points.map{InkPoint(x:$0.x+delta.x,y:$0.y+delta.y,pressure:$0.pressure)}};rebuildGeometry()}
    func deleteSelected(){guard hasSelection else{return};recordMutation();for id in selectedObjectIDs{objectStore.remove(id:id)};for i in selectedStrokeIndices.sorted(by:> ) where committedStrokes.indices.contains(i){committedStrokes.remove(at:i)};selectedObjectIDs=[];selectedStrokeIndices=[];rebuildGeometry()}
    func mtkView(_ view:MTKView,drawableSizeWillChange size:CGSize){updateUniformBuffer(for:size)}
    func draw(in view:MTKView){guard let pass=view.currentRenderPassDescriptor,let drawable=view.currentDrawable,let cb=commandQueue.makeCommandBuffer(),let encoder=cb.makeRenderCommandEncoder(descriptor:pass) else{return};pass.colorAttachments[0].clearColor=MTLClearColor(red:Double(backgroundColor.x),green:Double(backgroundColor.y),blue:Double(backgroundColor.z),alpha:1);updateUniformBuffer(for:view.drawableSize);encoder.setRenderPipelineState(pipelineState);if let b=vertexBuffer{encoder.setVertexBuffer(b,offset:0,index:0)};if let b=uniformBuffer{encoder.setVertexBuffer(b,offset:0,index:1)};if !vertices.isEmpty{encoder.drawPrimitives(type:.triangle,vertexStart:0,vertexCount:vertices.count)};encoder.endEncoding();cb.present(drawable);cb.commit()}
    private func rebuildGeometry(){var out:[InkVertex]=[];appendBackground(to:&out);for s in committedStrokes{appendStroke(s.points,style:s.style,to:&out)};appendObjects(to:&out);if let r=selectionBounds(){appendSelection(r,to:&out)};if !activeStroke.isEmpty{appendStroke(activeStroke,style:penStyle,to:&out)};vertices=out;vertexBuffer=vertices.isEmpty ? nil : device.makeBuffer(bytes:vertices,length:vertices.count*MemoryLayout<InkVertex>.stride,options:.storageModeShared)}
    private func appendObjects(to out:inout[InkVertex]){for o in objectStore.objects{let p=objectStore.transformedPoints(of:o);guard p.count>=2 else{continue};let color=metalColor(o.style);switch o.kind{case .line,.arrow:appendLine(viewPoint(from:SIMD2(Float(p[0].x),Float(p[0].y))),viewPoint(from:SIMD2(Float(p[1].x),Float(p[1].y))),width:Float(max(0.5,o.style.strokeWidth)),color:color,to:&out);case .polygon:if p.count>=2{for i in 0..<p.count{let j=(i+1)%p.count;appendLine(viewPoint(from:SIMD2(Float(p[i].x),Float(p[i].y))),viewPoint(from:SIMD2(Float(p[j].x),Float(p[j].y))),width:Float(max(0.5,o.style.strokeWidth)),color:color,to:&out)} };case .parameterizedTriangle:if p.count>=3{for i in 0..<3{let j=(i+1)%3;appendLine(viewPoint(from:SIMD2(Float(p[i].x),Float(p[i].y))),viewPoint(from:SIMD2(Float(p[j].x),Float(p[j].y))),width:Float(max(0.5,o.style.strokeWidth)),color:color,to:&out)}};case .dynamicAngle:appendDynamicAngle(o,color:color,to:&out);default:break}}}
    private func appendDynamicAngle(_ object:GraphicObject,color:SIMD4<Float>,to out:inout[InkVertex]){guard let dynamic=object.dynamicAngleModel else{return};let p=dynamic.model.points;guard let v=p.first(where:{$0.id == dynamic.vertexPointID}),let a=p.first(where:{$0.id == dynamic.startPointID}),let b=p.first(where:{$0.id == dynamic.endPointID}) else{return};let tv=objectPoint(v.position,in:object),ta=objectPoint(a.position,in:object),tb=objectPoint(b.position,in:object);appendLine(viewPoint(from:SIMD2(Float(tv.x),Float(tv.y))),viewPoint(from:SIMD2(Float(ta.x),Float(ta.y))),width:Float(max(0.5,object.style.strokeWidth)),color:color,to:&out);appendLine(viewPoint(from:SIMD2(Float(tv.x),Float(tv.y))),viewPoint(from:SIMD2(Float(tb.x),Float(tb.y))),width:Float(max(0.5,object.style.strokeWidth)),color:color,to:&out);let r=min(hypot(ta.x-tv.x,ta.y-tv.y),hypot(tb.x-tv.x,tb.y-tv.y))*0.32;guard r>2 else{return};let start=atan2(ta.y-tv.y,ta.x-tv.x);let end=atan2(tb.y-tv.y,tb.x-tv.x);var delta=end-start;while delta<0{delta += 2*CGFloat.pi};if delta>CGFloat.pi{delta -= 2*CGFloat.pi};let steps=max(8,Int(abs(delta)*r/8));var prev=CGPoint(x:tv.x+r*cos(start),y:tv.y+r*sin(start));for i in 1...steps{let t=CGFloat(i)/CGFloat(steps);let q=CGPoint(x:tv.x+r*cos(start+delta*t),y:tv.y+r*sin(start+delta*t));appendLine(viewPoint(from:SIMD2(Float(prev.x),Float(prev.y))),viewPoint(from:SIMD2(Float(q.x),Float(q.y))),width:Float(max(0.5,object.style.strokeWidth*0.9)),color:color,to:&out);prev=q};let textRadius=r+18;_ = textRadius}
    private func objectPoint(_ point:CGPoint,in object:GraphicObject)->CGPoint{let center=object.transform.rotationCenter;let translated=CGPoint(x:point.x-center.x,y:point.y-center.y);let scaled=CGPoint(x:translated.x*object.transform.scale.width,y:translated.y*object.transform.scale.height);let c=cos(object.transform.rotation),s=sin(object.transform.rotation);return CGPoint(x:scaled.x*c-scaled.y*s+center.x+object.transform.position.x,y:scaled.x*s+scaled.y*c+center.y+object.transform.position.y)}
    private func appendBackground(to out:inout[InkVertex]){guard backgroundPattern != 0 else{return};let color=SIMD4<Float>(0.82,0.84,0.88,0.55);let step:Float=backgroundPattern == 3 ? 24:32;let e:Float=2000;if backgroundPattern == 1{var y:Float = -e;while y<=e{appendLine(viewPoint(from:SIMD2(-e,y)),viewPoint(from:SIMD2(e,y)),width:0.55,color:color,to:&out);y+=step}}else{var x:Float = -e;while x<=e{appendLine(viewPoint(from:SIMD2(x,-e)),viewPoint(from:SIMD2(x,e)),width:0.45,color:color,to:&out);x+=step};var y:Float = -e;while y<=e{appendLine(viewPoint(from:SIMD2(-e,y)),viewPoint(from:SIMD2(e,y)),width:0.45,color:color,to:&out);y+=step}}}
    private func appendSelection(_ r:CGRect,to out:inout[InkVertex]){let c=SIMD4<Float>(0.1,0.45,1,0.75),a=viewPoint(from:SIMD2(Float(r.minX),Float(r.minY))),b=viewPoint(from:SIMD2(Float(r.maxX),Float(r.maxY))),p0=SIMD2(a.x,a.y),p1=SIMD2(b.x,a.y),p2=SIMD2(b.x,b.y),p3=SIMD2(a.x,b.y);appendLine(p0,p1,width:1.5,color:c,to:&out);appendLine(p1,p2,width:1.5,color:c,to:&out);appendLine(p2,p3,width:1.5,color:c,to:&out);appendLine(p3,p0,width:1.5,color:c,to:&out);for p in[p0,p1,p2,p3]{disk(p,5,c,to:&out)};let rot=SIMD2((a.x+b.x)/2,a.y-28);appendLine(SIMD2((a.x+b.x)/2,a.y),rot,width:1,color:c,to:&out);disk(rot,7,c,to:&out)}
    private func updateUniformBuffer(for size:CGSize){var u=Uniforms(viewportSize:SIMD2(Float(size.width),Float(size.height)));if uniformBuffer==nil{uniformBuffer=device.makeBuffer(length:MemoryLayout<Uniforms>.stride,options:.storageModeShared)};if let b=uniformBuffer{memcpy(b.contents(),&u,MemoryLayout<Uniforms>.stride)}}
    private func appendLine(_ a:SIMD2<Float>,_ b:SIMD2<Float>,width:Float,color:SIMD4<Float>,to out:inout[InkVertex]){let d=b-a,l=max(simd_length(d),0.001),n=SIMD2(-d.y,d.x)/l*wmax(width);triangle(a+n,a-n,b+n,color:color,to:&out);triangle(b+n,a-n,b-n,color:color,to:&out)}
    private func wmax(_ value:Float)->Float{max(value,0.5)}
    private func triangle(_ a:SIMD2<Float>,_ b:SIMD2<Float>,_ c:SIMD2<Float>,color:SIMD4<Float>,to out:inout[InkVertex]){out.append(InkVertex(position:SIMD2(a.x,a.y),color:color));out.append(InkVertex(position:SIMD2(b.x,b.y),color:color));out.append(InkVertex(position:SIMD2(c.x,c.y),color:color))}
    private func disk(_ center:SIMD2<Float>,_ radius:Float,_ color:SIMD4<Float>,to out:inout[InkVertex]){let steps=20;var prev=SIMD2(center.x+radius,center.y);for i in 1...steps{let t=Float(i)/Float(steps)*2*Float.pi;let next=SIMD2(center.x+cos(t)*radius,center.y+sin(t)*radius);triangle(center,prev,next,color:color,to:&out);prev=next}}
    private func appendStroke(_ s:[InkPoint],style:PenStyle,to out:inout[InkVertex]){guard !s.isEmpty else{return};let color=metalColor(style);if s.count>1{for i in 0..<(s.count-1){let p=s[i],q=s[i+1],dx=q.x-p.x,dy=q.y-p.y,l=max(sqrt(dx*dx+dy*dy),0.001),nx=-dy/l,ny=dx/l,w0=strokeWidth(p.pressure,style),w1=strokeWidth(q.pressure,style),a=viewPoint(from:SIMD2(p.x+nx*w0,p.y+ny*w0)),b=viewPoint(from:SIMD2(p.x-nx*w0,p.y-ny*w0)),c=viewPoint(from:SIMD2(q.x+nx*w1,q.y+ny*w1)),d=viewPoint(from:SIMD2(q.x-nx*w1,q.y-ny*w1));triangle(a,b,c,color:color,to:&out);triangle(c,b,d,color:color,to:&out)}};for p in s{disk(viewPoint(from:SIMD2(p.x,p.y)),strokeWidth(p.pressure,style),color,to:&out)}}
    private func strokeWidth(_ pressure:Float,_ style:PenStyle)->Float{max(0.75,style.width*(0.45+0.55*max(0,min(1,pressure))))}
    private func metalColor(_ style:PenStyle)->SIMD4<Float>{SIMD4(Float(style.color.red),Float(style.color.green),Float(style.color.blue),Float(style.opacity))}
    private func metalColor(_ color:RGBAColor)->SIMD4<Float>{SIMD4(Float(color.red),Float(color.green),Float(color.blue),Float(color.alpha))}
    private func bounds(_ points:[InkPoint])->CGRect?{guard let f=points.first else{return nil};var x0=f.x,x1=f.x,y0=f.y,y1=f.y;for q in points{x0=min(x0,q.x);x1=max(x1,q.x);y0=min(y0,q.y);y1=max(y1,q.y)};return CGRect(x:CGFloat(x0),y:CGFloat(y0),width:CGFloat(x1-x0),height:CGFloat(y1-y0))}
}
