<?php
namespace MathCourse\Admin;
defined('ABSPATH') || exit;
use MathCourse\Tutor\Adapter;
use MathCourse\Access\Activation_Service;
class Activation_Page {
 public function __construct(){add_action('admin_post_mathcourse_generate_codes',array($this,'generate'));}
 public function render(){if(!current_user_can('manage_options'))return;$courses=(new Adapter())->get_courses(true,-1);$codes=get_transient('mathcourse_generated_codes_'.get_current_user_id());if($codes)delete_transient('mathcourse_generated_codes_'.get_current_user_id());global $wpdb;$table=$wpdb->prefix.'mathcourse_activation_codes';$unused=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$table} WHERE status='unused'");$used=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$table} WHERE status='used'");?>
<div class="wrap mathcourse-admin-wrap mathcourse-activation-admin"><div class="mathcourse-admin-header"><h1>课程激活码</h1><p>生成与课程绑定的一次性激活码。学员使用激活码注册后，会自动获得对应课程授权。</p></div>
<div class="mathcourse-card"><h2>生成激活码</h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" class="mathcourse-activation-form"><?php wp_nonce_field('mathcourse_generate_codes'); ?><input type="hidden" name="action" value="mathcourse_generate_codes"><p><label>课程</label><select name="course_id" required><option value="">请选择课程</option><?php foreach($courses as $course): ?><option value="<?php echo esc_attr($course->ID); ?>"><?php echo esc_html($course->post_title); ?></option><?php endforeach; ?></select></p><p><label>生成数量</label><input type="number" name="quantity" min="1" max="500" value="10" required></p><p><label>有效期</label><select name="expiry"><option value="0">不限（推荐）</option><option value="365">生成后 365 天</option><option value="90">生成后 90 天</option><option value="30">生成后 30 天</option></select></p><p><button class="button button-primary" type="submit">生成激活码</button></p></form></div>
<?php if($codes): ?><div class="mathcourse-card"><h2>本次生成的激活码</h2><p>激活码只在这里显示一次，请复制保存后再发给学员。数据库不保存明文激活码。</p><textarea class="mathcourse-code-output" rows="12" readonly><?php echo esc_textarea(implode("\n",$codes)); ?></textarea></div><?php endif; ?>
<div class="mathcourse-stat-grid"><div class="mathcourse-stat-card"><div class="mathcourse-stat-title">未使用</div><div class="mathcourse-stat-num"><?php echo esc_html($unused); ?></div></div><div class="mathcourse-stat-card"><div class="mathcourse-stat-title">已使用</div><div class="mathcourse-stat-num"><?php echo esc_html($used); ?></div></div></div></div><?php }
 public function generate(){if(!current_user_can('manage_options'))wp_die('无权限');check_admin_referer('mathcourse_generate_codes');$course_id=absint($_POST['course_id']??0);$quantity=max(1,min(500,absint($_POST['quantity']??10)));$expiry=absint($_POST['expiry']??0);$expires=$expiry>0?gmdate('Y-m-d H:i:s',time()+$expiry*DAY_IN_SECONDS):null;$codes=(new Activation_Service())->generate($course_id,$quantity,$expires);set_transient('mathcourse_generated_codes_'.get_current_user_id(),$codes,10*MINUTE_IN_SECONDS);wp_safe_redirect(admin_url('admin.php?page=mathcourse-activation'));exit;}
}
